#!/usr/bin/env bash
# Bug-history mutant benchmark: can each fuzzing axis rediscover KNOWN bugs?
#
#   fuzz/mutantbench.sh [--n N] [--axes a,b,c] [--seed S] [--timeout SECS] SHA [SHA...]
#
# For each SHA (a historical *fix* commit), this script:
#   1. creates a detached temp worktree at HEAD and `git revert --no-commit SHA`
#      there — producing a "mutant" interpreter that once again contains the bug
#      the commit fixed. Only src/ is left reverted: fuzz/, test/, benchmark/,
#      bin/ and docs/ are restored to HEAD so the harness that judges the mutant
#      is always the current one. A revert conflict is recorded and skipped, not
#      resolved.
#   2. sets up the mutant's own fuzz env (Pkg.develop the mutant checkout) and
#      confirms the mutant still loads (`using JuliaInterpreter`). The selftest
#      is deliberately NOT run: it is slow per mutant and may legitimately fail
#      on a mutant, which is the point of the exercise, not a setup error.
#   3. runs every requested axis (`run.jl --fresh --noshrink --nosync`, findings
#      and journal inside the temp worktree, so nothing pollutes the repo).
#      Exit 2 = the axis rediscovered something (findings count + first
#      finding's class-fingerprint recorded); exit 0 = not detected at this n;
#      anything else = the run crashed (log tail recorded).
#   4. appends one TSV row per (mutant, axis) to fuzz/mutantbench-results.tsv
#      and regenerates the matrix in fuzz/mutantbench-report.md below the
#      `<!-- mutantbench:matrix -->` marker (hand-written text above the marker
#      is preserved).
#   5. removes the temp worktree, also on failure (trap).
#
# Axes (per-axis args mirror fuzz/longrun.sh batch_args; --n overrides count):
#   native      --engine native --modes both
#   native-rec  --engine native --modes rec
#   native-cmp  --engine native --modes cmp
#   step | evalcode | corpus | split | call
#
# A detection here is evidence the axis has teeth against that bug class at
# that n; a non-detection at n=N is a *result* — record it, do not quietly
# re-run at larger n and report only the success.

set -uo pipefail

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPTDIR")"
RESULTS="$SCRIPTDIR/mutantbench-results.tsv"
REPORT="$SCRIPTDIR/mutantbench-report.md"
MARKER='<!-- mutantbench:matrix -->'

# Prefer the juliaup julia if a bare `julia` is not first on PATH.
if [ -z "${JULIA_CMD:-}" ]; then
    if command -v julia >/dev/null 2>&1; then JULIA_CMD=julia
    elif [ -x "$HOME/.juliaup/bin/julia" ]; then JULIA_CMD="$HOME/.juliaup/bin/julia"
    else echo "mutantbench: no julia found (set JULIA_CMD)" >&2; exit 1; fi
fi

N=1000
AXES="native,step"
SEED=1000000
TIMEOUT=1800
REPORT_ONLY=0
SHAS=()
while [ $# -gt 0 ]; do
    case "$1" in
        --n)       N="$2"; shift 2 ;;
        --axes)    AXES="$2"; shift 2 ;;
        --seed)    SEED="$2"; shift 2 ;;
        --timeout) TIMEOUT="$2"; shift 2 ;;
        --report-only) REPORT_ONLY=1; shift ;;   # just regenerate the matrix from the TSV
        -*)        echo "mutantbench: unknown flag $1" >&2; exit 1 ;;
        *)         SHAS+=("$1"); shift ;;
    esac
done
if [ "$REPORT_ONLY" -eq 0 ] && [ ${#SHAS[@]} -eq 0 ]; then
    echo "mutantbench: no mutant SHAs given (or use --report-only)" >&2; exit 1
fi

axis_args() {
    case "$1" in
        native)     echo "--engine native --modes both" ;;
        native-rec) echo "--engine native --modes rec" ;;
        native-cmp) echo "--engine native --modes cmp" ;;
        step)       echo "--engine step" ;;
        evalcode)   echo "--engine evalcode" ;;
        corpus)     echo "--engine corpus --maxsplice 4" ;;
        split)      echo "--engine split" ;;
        call)       echo "--engine call" ;;
        *) echo "unknown axis $1" >&2; return 1 ;;
    esac
}

record() {  # sha axis n verdict nfindings first_finding wall
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$(date -u +%FT%TZ)" >> "$RESULTS"
}

# --- report generation -------------------------------------------------------
regen_report() {
    local tmp="$REPORT.tmp" mline
    if [ -f "$REPORT" ] && grep -qF "$MARKER" "$REPORT"; then
        mline=$(grep -nF "$MARKER" "$REPORT" | head -1 | cut -d: -f1)
        head -n "$mline" "$REPORT" > "$tmp"
    else
        {
            echo "# Bug-history mutant benchmark"
            echo
            echo "Generated by \`fuzz/mutantbench.sh\`. Text above the marker is preserved."
            echo
            echo "$MARKER"
        } > "$tmp"
    fi
    {
        echo
        echo "_Matrix regenerated $(date -u +%FT%TZ) from \`fuzz/mutantbench-results.tsv\`._"
        echo
        awk -F'\t' -v root="$ROOT" '
        {
            sha=$1; axis=$2; n=$3; verdict=$4; nf=$5; first=$6; wall=$7
            key=sha SUBSEP axis
            if (!(sha in seen_sha)) { seen_sha[sha]=1; shas[++nsha]=sha }
            if (axis != "-" && !(axis in seen_ax)) { seen_ax[axis]=1; axes[++nax]=axis }
            # last write wins per cell
            if (verdict=="detected")      cell[key]="detected@" n " (" nf ": " first ", " wall "s)"
            else if (verdict=="none")     cell[key]="not detected@" n " (" wall "s)"
            else if (verdict=="crashed")  cell[key]="crashed@" n " (" wall "s)"
            else if (verdict=="revert-conflict") conflict[sha]="revert-conflict, skipped"
            else if (verdict=="no-src-change")   conflict[sha]="no src/ change after revert, skipped"
            else if (verdict=="load-failure")    conflict[sha]="mutant failed to load, skipped"
            else if (verdict=="invalid-mutant")  conflict[sha]="invalid mutant (revert artifact), skipped"
            else cell[key]=verdict "@" n
        }
        END {
            printf "| mutant (revert of) | description |"
            for (j=1; j<=nax; j++) printf " %s |", axes[j]
            printf "\n|---|---|"
            for (j=1; j<=nax; j++) printf "---|"
            printf "\n"
            for (i=1; i<=nsha; i++) {
                sha=shas[i]
                desc=""
                cmd="git -C " root " log -1 --format=%s " sha " 2>/dev/null"
                cmd | getline desc; close(cmd)
                printf "| %s | %s |", sha, desc
                if (sha in conflict) {
                    for (j=1; j<=nax; j++) printf " %s |", conflict[sha]
                } else {
                    for (j=1; j<=nax; j++) {
                        key=sha SUBSEP axes[j]
                        printf " %s |", (key in cell) ? cell[key] : "—"
                    }
                }
                printf "\n"
            }
        }' "$RESULTS"
        echo
        echo "Cells: \`detected@N (k: class-fingerprint, secs)\` = the axis produced k"
        echo "finding(s) within N candidates; \`not detected@N\` = clean run at that n;"
        echo "\`—\` = that (mutant, axis) pair has not been run."
        echo
        echo "Rerun the full matrix (larger n as compute allows; these are the mutants"
        echo "whose reverts apply cleanly at HEAD *and* are semantically valid — see the"
        echo "curation table for the conflicting/skipped rest, including 73d94c4,"
        echo "which reverts cleanly but is a revert artifact, not the historical bug):"
        echo
        echo '```sh'
        echo "fuzz/mutantbench.sh --n 10000 --axes split 1e52e3e"
        echo "fuzz/mutantbench.sh --n 10000 --axes step a3eabb3 95cc23c"
        echo "fuzz/mutantbench.sh --n 10000 --axes native 76605f6"
        echo "fuzz/mutantbench.sh --n 10000 --axes native-rec beeb4b0"
        echo "fuzz/mutantbench.sh --n 10000 --axes native-cmp 94cc282"
        echo '```'
    } >> "$tmp"
    mv "$tmp" "$REPORT"
}

# --- worktree lifecycle ------------------------------------------------------
CURRENT_WT=""
cleanup() {
    if [ -n "$CURRENT_WT" ] && [ -d "$CURRENT_WT" ]; then
        git -C "$ROOT" worktree remove --force "$CURRENT_WT" >/dev/null 2>&1 \
            || rm -rf "$CURRENT_WT"
        git -C "$ROOT" worktree prune >/dev/null 2>&1
    fi
    CURRENT_WT=""
}
trap cleanup EXIT INT TERM

MBTMP="${MUTANTBENCH_TMPDIR:-$(mktemp -d "${TMPDIR:-/tmp}/mutantbench.XXXXXX")}"
mkdir -p "$MBTMP"
LOGDIR="$MBTMP/logs"
mkdir -p "$LOGDIR"

run_mutant() {
    local sha="$1" wt log setup_ok=1
    wt="$MBTMP/mut-$sha"
    CURRENT_WT="$wt"
    echo "=== mutant $sha: $(git -C "$ROOT" log -1 --format=%s "$sha") ==="

    git -C "$ROOT" worktree remove --force "$wt" >/dev/null 2>&1 || true
    rm -rf "$wt"
    if ! git -C "$ROOT" worktree add --detach "$wt" HEAD >/dev/null 2>&1; then
        echo "  worktree add failed"; record "$sha" "-" "$N" "crashed" 0 "worktree-add-failed" 0
        cleanup; return 1
    fi

    if ! git -C "$wt" revert --no-commit "$sha" >/dev/null 2>&1; then
        git -C "$wt" revert --abort >/dev/null 2>&1 || true
        echo "  revert-conflict, skipped"
        record "$sha" "-" "$N" "revert-conflict" 0 "-" 0
        cleanup; return 0
    fi
    # The mutant is the src/ half of the revert only: the judging harness
    # (fuzz/), tests and everything else stay at HEAD.
    git -C "$wt" checkout HEAD -- fuzz/ test/ benchmark/ bin/ docs/ 2>/dev/null || true
    # fuzz/findings ships force-committed historical findings (see
    # preserve-findings.sh) — including, for a mutant, the very finding the
    # reverted fix came from, under the same class-fingerprint dir name. Wipe
    # them so everything present after a run was written BY that run (the runs
    # use --fresh, so the dedup set never read the disk either way).
    rm -rf "$wt/fuzz/findings"
    if git -C "$wt" diff --quiet HEAD -- src/; then
        echo "  no src/ change after revert, skipped"
        record "$sha" "-" "$N" "no-src-change" 0 "-" 0
        cleanup; return 0
    fi

    # Mutant fuzz env: dev the mutant checkout into its own fuzz project, then
    # prove the mutant loads at all. (No selftest — see header.)
    log="$LOGDIR/$sha-setup.log"
    (cd "$wt" && $JULIA_CMD --project=fuzz -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()' \
        && $JULIA_CMD --project=fuzz -e 'using JuliaInterpreter') >"$log" 2>&1 || setup_ok=0
    if [ "$setup_ok" -eq 0 ]; then
        echo "  mutant failed to load; log tail:"
        tail -5 "$log" | sed 's/^/    /'
        record "$sha" "-" "$N" "load-failure" 0 "-" 0
        cleanup; return 0
    fi

    # Validity probe: a single-commit revert can be textually clean but
    # semantically inconsistent — e.g. it removes a helper that a LATER commit
    # also calls, so the mutant dies with an internal UndefVarError on the most
    # trivial debugger use (observed with 73d94c4/is_next_line_stop). Such a
    # mutant measures revert-artifact detection, not bug rediscovery, so it is
    # recorded as invalid and skipped. A revert whose *bug* breaks this trivial
    # probe would be misclassified too — inspect the probe error in the setup
    # log before trusting an invalid-mutant verdict.
    log="$LOGDIR/$sha-probe.log"
    if ! (cd "$wt" && $JULIA_CMD --project=fuzz -e '
        using JuliaInterpreter
        @assert (JuliaInterpreter.@interpret sum([1,2,3])) == 6
        f(x) = (y = x + 1; z = y * 2; z)
        let fr = JuliaInterpreter.enter_call(f, 3)
            while true
                r = JuliaInterpreter.debug_command(fr, :n)
                r === nothing && break
                fr = r[1]
            end
        end
        println("VALIDITY-OK")') >"$log" 2>&1; then
        echo "  validity probe failed (semantically inconsistent revert?); log tail:"
        tail -3 "$log" | sed 's/^/    /'
        record "$sha" "-" "$N" "invalid-mutant" 0 "-" 0
        cleanup; return 0
    fi

    local axis args rc t0 t1 wall nf first
    for axis in ${AXES//,/ }; do
        args="$(axis_args "$axis")" || { record "$sha" "$axis" "$N" "crashed" 0 "bad-axis" 0; continue; }
        log="$LOGDIR/$sha-$axis.log"
        echo "  axis $axis (n=$N, timeout=${TIMEOUT}s) ..."
        t0=$(date +%s)
        (cd "$wt" && timeout "$TIMEOUT" $JULIA_CMD --project=fuzz fuzz/run.jl $args \
            --n "$N" --seed "$SEED" --fresh --noshrink --nosync \
            --journaldir "fuzz/journal-mb-$axis") >"$log" 2>&1
        rc=$?
        t1=$(date +%s); wall=$((t1 - t0))
        # Findings written by this run (worktree starts with no findings/).
        nf=0; first="-"
        if [ -d "$wt/fuzz/findings" ]; then
            # top-level finding dirs; the julia/ bucket is reference-side, not SUT
            nf=$(find "$wt/fuzz/findings" -mindepth 1 -maxdepth 1 -type d ! -name julia | wc -l)
            first=$(find "$wt/fuzz/findings" -mindepth 1 -maxdepth 1 -type d ! -name julia \
                    -printf '%f\n' | sort | head -1)
            [ -n "$first" ] || first="-"
        fi
        if [ "$rc" -eq 2 ] && [ "$nf" -gt 0 ]; then
            echo "    DETECTED: $nf finding(s), first: $first (${wall}s)"
            record "$sha" "$axis" "$N" "detected" "$nf" "$first" "$wall"
        elif [ "$rc" -eq 0 ]; then
            echo "    not detected at n=$N (${wall}s)"
            record "$sha" "$axis" "$N" "none" 0 "-" "$wall"
        else
            echo "    crashed (exit $rc, ${wall}s); log tail:"
            tail -5 "$log" | sed 's/^/    /'
            record "$sha" "$axis" "$N" "crashed" "$nf" "exit=$rc" "$wall"
        fi
        # Preserve evidence outside the doomed worktree for post-hoc inspection.
        if [ "$nf" -gt 0 ]; then
            mkdir -p "$MBTMP/evidence/$sha-$axis"
            cp -r "$wt/fuzz/findings/." "$MBTMP/evidence/$sha-$axis/" 2>/dev/null || true
        fi
    done
    cleanup
    return 0
}

touch "$RESULTS"
for sha in ${SHAS[@]+"${SHAS[@]}"}; do
    run_mutant "$sha"
done
regen_report
echo "mutantbench: results in $RESULTS, matrix in $REPORT"
echo "mutantbench: logs and finding evidence under $MBTMP (not committed)"
