# FuzzJI reproducer — interp_only_throw (interp mode: corpusvalue)
# seed: 1785779695500200614
# walk seed: 5371269379363954215
# julia: 1.12.6
# detail: interp threw ErrorException: invalid redefinition of constant Future
# Run with: julia --project=<repo>/fuzz <this file>
include(joinpath(@__DIR__, "..", "..", "reprolib.jl"))
const SRC = "using Test, Distributed, Random, Logging, Libdl\nusing REPL\nusing .ConflictingBindings\nFooBase_module = :FooBase4b3a94a1a081a8cb\n#= none:3 =# Core.@doc \"The `Future` module implements future behavior of already existing functions,\\nwhich will replace the current version in a future release of Julia.\" module Future\n    #= none:5 =#\n    #= none:7 =#\n    using Random\n    #= none:14 =#\n    #= none:14 =# Core.@doc \"    Future.copy!(dst, src) -> dst\\n\\nCopy `src` into `dst`.\\n\\n!!! compat \\\"Julia 1.1\\\"\\n    This function has moved to `Base` with Julia 1.1, consider using `copy!(dst, src)` instead.\\n    `Future.copy!` will be deprecated in the future.\\n\" copy!(dst::AbstractSet, src::AbstractSet) = begin\n                #= none:23 =#\n                Base.copy!(dst, src)\n            end\n    #= none:24 =#\n    copy!(dst::AbstractDict, src::AbstractDict) = begin\n            #= none:24 =#\n            Base.copy!(dst, src)\n        end\n    #= none:25 =#\n    copy!(dst::AbstractArray, src::AbstractArray) = begin\n            #= none:25 =#\n            Base.copy!(dst, src)\n        end\n    #= none:30 =#\n    #= none:30 =# Core.@doc \"    randjump(r::MersenneTwister, steps::Integer) -> MersenneTwister\\n\\nCreate an initialized `MersenneTwister` object, whose state is moved forward\\n(without generating numbers) from `r` by `steps` steps.\\nOne such step corresponds to the generation of two `Float64` numbers.\\nFor each different value of `steps`, a large polynomial has to be generated internally.\\nOne is already pre-computed for `steps=big(10)^20`.\\n\" function randjump(r::MersenneTwister, steps::Integer)\n            #= none:39 =#\n            #= none:40 =#\n            j = Random._randjump(r, Random.DSFMT.calc_jump(steps))\n            #= none:41 =#\n            j.adv_jump += 2 * big(steps)\n            #= none:42 =#\n            j\n        end\n    end\n#= none:391 =# @testset \"issue #15723\" begin\n        #= none:392 =#\n        #= none:392 =# @test findfirst(isequal('('), \"⨳(\") == 4\n        #= none:393 =#\n        #= none:393 =# @test findnext(isequal('('), \"(⨳(\", 2) == 5\n        #= none:394 =#\n        #= none:394 =# @test findlast(isequal('('), \"(⨳(\") == 5\n        #= none:395 =#\n        #= none:395 =# @test findprev(isequal('('), \"(⨳(\", 2) == 1\n        #= none:397 =#\n        #= none:397 =# @test #= none:397 =# @inferred(findall(isequal('a'), \"éa\") == [3])\n        #= none:398 =#\n        #= none:398 =# @test #= none:398 =# @inferred(findall(isequal('€'), \"€€\") == [1, 4])\n        #= none:399 =#\n        #= none:399 =# @test #= none:399 =# @inferred(isempty(findall(isequal('é'), \"\")))\n    end"
reprocorpus(SRC)
